on:
  push:
    tags:
      - "v*.*.*"

permissions:
  contents: write

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: bjia56/setup-cosmocc@c0097c34319baeca1b41cc857ec5c643f2f5baf6
        with:
          version: "4.0.2"

      - name: Install dependencies
        uses: ./.github/actions/install-dependencies

      - name: Build release
        run: make dependencies compute-bounding-box.exe CXX=cosmoc++ CFLAGS="-O3"

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: compute-bounding-box.exe
          path: compute-bounding-box.exe

  release:
    name: Create GitHub Release
    needs: build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: compute-bounding-box.exe
          path: artifacts/

      - name: Create release
        uses: softprops/action-gh-release@v2
        with:
          files: artifacts/compute-bounding-box.exe
          generate_release_notes: true
